apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-annotations-injection.fullname" . }}
  labels:
    {{- include "ingress-annotations-injection.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      name: https-webhook
  selector:
    {{- include "ingress-annotations-injection.selectorLabels" . | nindent 4 }}
